import type { AppData } from "./types";

export const initialData: AppData = {
  clipboardItems: [
    {
      id: 1,
      kind: "text",
      title: "PC 端效率辅助工具",
      content: "PC 端效率辅助工具 —— 剪切板管理、快捷短语、翻译、桌面悬浮窗形态，关闭后驻留系统托盘。",
      cached: true,
      pinned: true,
      createdAt: "2026-05-19 00:00",
      updatedAt: "2026-05-19 00:00",
      sizeBytes: 142,
    },
    {
      id: 2,
      kind: "link",
      title: "GitHub",
      content: "https://github.com/",
      cached: true,
      pinned: false,
      createdAt: "2026-05-18 23:48",
      updatedAt: "2026-05-18 23:48",
      sizeBytes: 19,
    },
    {
      id: 3,
      kind: "image",
      title: "界面截图",
      content: "clipboard-image-20260518.png",
      previewPath: "",
      cached: true,
      pinned: false,
      createdAt: "2026-05-18 23:39",
      updatedAt: "2026-05-18 23:39",
      sizeBytes: 248900,
    },
    {
      id: 4,
      kind: "file",
      title: "copy-creator(1).exe",
      content: "D:\\Downloads\\copy-creator(1).exe",
      originalPath: "D:\\Downloads\\copy-creator(1).exe",
      cachedPath: ".\\data\\cache\\files\\copy-creator(1).exe",
      cached: true,
      pinned: false,
      createdAt: "2026-05-18 23:39",
      updatedAt: "2026-05-18 23:39",
      sizeBytes: 42_000_000,
    },
  ],
  phraseGroups: [
    { id: 1, name: "AI 指令", sortOrder: 1 },
    { id: 2, name: "客服短语", sortOrder: 2 },
    { id: 3, name: "常用链接", sortOrder: 3 },
  ],
  phrases: [
    { id: 1, groupId: 1, title: "/context", content: "查看上下文", updatedAt: "2026-05-19 01:00" },
    { id: 2, groupId: 1, title: "/compact", content: "压缩上下文", updatedAt: "2026-05-19 01:00" },
    { id: 3, groupId: 1, title: "/resume", content: "查看历史会话", updatedAt: "2026-05-19 01:00" },
    { id: 4, groupId: 1, title: "/clear", content: "清除上下文", updatedAt: "2026-05-19 01:00" },
  ],
  settings: {
    language: "zh",
    theme: "light",
    density: "normal",
    startOnBoot: false,
    hideOnClose: true,
    saveDays: 30,
    maxItems: 1000,
    recordText: true,
    recordLinks: true,
    recordImages: true,
    recordFiles: true,
    sensitiveDetection: false,
    imageCachePolicy: "follow_history",
    fileMaxMb: 200,
    cacheMaxGb: 5,
    cacheCleanup: "follow_history",
    quickHotkey: "",
    quickShowClipboard: true,
    quickShowPhrases: true,
    apiBaseUrl: "https://api.deepseek.com",
    apiKeyConfigured: false,
    modelName: "deepseek-chat",
    defaultTargetLanguage: "English",
  },
};
